import JackfruitsCard from '@/components/JacksFruitsCard/JackfruitsCard';


export const metadata = {
  title: "all-Jackfruits",
  description: "Generated by Jackfruits",
};

const AllJackfruits = async() => {

    const res = await fetch("https://assingment-8-jacfruits.vercel.app/data.json",{
        cache: "no-store"
    });
    const allfruits = await res.json();
   
    return (
        <div className=' max-w-[96%] lg:max-w-[80%] mx-auto my-10'>

             <h1 className='text-4xl font-bold text-transparent bg-linear-65 from-purple-500 to-pink-500 bg-clip-text my-6'>All jackfruit is the largest tree fruit.</h1>
           <div className='grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-3 gap-8'>

            {
                allfruits.map((fruit) => <JackfruitsCard key={fruit} fruit={fruit}></JackfruitsCard>)
            }

           </div>
        </div>
    );
};

export default AllJackfruits;