
import Image from "next/image";
import Link from "next/link";
import { FcRating } from "react-icons/fc";


export const metadata = {
  title: "Jackfruits-Details-Page",
  description: "Generated by Jackfruits",
};
const Detailspage = async ({ params }) => {
  const { id } = await params;
  // console.log(data);
  const res = await fetch("https://assingment-8-jacfruits.vercel.app/data.json");
  const fruits = await res.json();

  const fruit = fruits.find((fruit) => fruit.id == id);

  // console.log(fruit);

  return (
    <div className="max-w-[96%] lg:max-w-[80%] mx-auto my-6">
      <h1 className="text-3xl text-center lg:text-left font-bold text-transparent bg-linear-65 from-purple-500 to-pink-500 bg-clip-text my-6">
        Jackfruits Details.
      </h1>

      <div className="card bg-base-100 w-full  lg:w-150 h-100 shadow-sm">
        <figure className="relative w-full aspect-square">
          <Image
            src={fruit.imageUrl}
            fill
            alt={fruit.title}
            className="object-cover"
          />
        </figure>
        <div className="space-y-4">
          <h2 className="card-title text-2xl font-bold">{fruit.title}</h2>
          <div className="flex justify-between items-center">
            <p className="text-xl font-bold text-black">Price :{fruit.price}</p>
            <p className="flex gap-2 items-center font-bold">
              <FcRating /> {fruit.rating}
            </p>
          </div>
          <div>
            <p>{fruit.prompt}</p>
          </div>
          <div>
            <h4 className="font-bold text-black">{fruit.createdAt}</h4>
          </div>
          <div className="">
            <Link href={"/"}>
              <button className="btn bg-linear-65 from-purple-500 to-pink-500 text-white">Go Back</button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Detailspage;
